version: '3'
services:

  app: 
    build: ./php
    ports: 
      - "8000:8000"
    volumes: 
      - ./php:/app
      - /app/vendor
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wedding
      MYSQL_USER: root
      MYSQL_PASSWORD: secret

volumes:
    db_data: